### PR TITLE
read the docs support

### PR DESCRIPTION
**Pull request by joachimwolff**
This PR adds the documentation on readthedocs. Have a look at: https://pygenometracks.readthedocs.io/en/rtd/index.html

### CODE REVIEW

**Comment by lldelisle** [comment]
Cool, thanks. Waiting for travis to approve.

**Comment by joachimwolff** [comment]
If you create an account on readthedocs I can add you there as a maintainer.

**Comment by lldelisle** [comment]
I think, as it is documentation this can be merged to master, no?

**Comment by lldelisle** [comment]
Should we remove what is in the README and just reference to the readthedocs?

**Comment by LeilyR** [comment]
No, I wouldn't. We need to keep some parts of it which are related to installation or a short summary of what the tool is about. We can also add a section for the documentation where we can give the link to its readthedoc. So basically it needs to get restructured. I can take care of it later on in Feb.

**Comment by lldelisle** [comment]
Yes sorry this is what I meant, truncate it... like in HiCExplorer or deepTools...

**Pull request merged**
