### PR TITLE
Fix lint isinstance

### PR DESCRIPTION
**Pull request by lldelisle**

### CODE REVIEW

**Comment by bgruening** [comment]
Maybe we need to install `importlib_metadata`?

**Comment by lldelisle** [comment]
Yes but I feel like the problem should not be solved in pyGenomeTracks but on HiCMatrix.

**Comment by lldelisle** [comment]
I think we should drop support for python 3.7

**Comment by bgruening** [comment]
Fine by me!

**Comment by lldelisle** [comment]
I tried to avoid python 3.7 support drop but conda could not solve the environment so I gave up.

**Pull request merged**
