### PR TITLE
Different color for negative values

### PR DESCRIPTION
**Pull request by Phlya**
Hi, as per https://github.com/deeptools/pyGenomeTracks/issues/32 - different colour for negative values. I started with just bigwig plots to see whether you agree with the strategy, and if it looks OK to you I can apply the same changes to bedgraph tracks too.

### CODE REVIEW

**Comment by fidelram** [comment]
Thanks for adding this, I will be happy to merge! And sorry for the delay I am travelling.

Can you fix the travis error? it is caused by some missing spaces around operators. 

Also, can you perhaps add an image to show the results?

**Comment by Phlya** [comment]
Thanks for the feedback, I will do that. BTW currently I have got a problem that my developmental installation doesn't work anymore due to this https://github.com/deeptools/HiCExplorer/issues/261

**Comment by Phlya** [comment]
To add an image, should I add some example data to the repository too? I'm presuming, you mean an image for readme?

**Comment by fidelram** [comment]
Thanks for fixing the errors. I was only thinking to you could add an image here, such that I can get an impression on how this is working. But if you want to edit the readme file and add and image that would be great too.

**Comment by Phlya** [comment]
Right. OK, yeah, I'll do that.

**Comment by Phlya** [comment]
Adding it to the readme is a bit complicated because I don't think there is a good example date file there already, so I would have to add some data, and I work with mouse, not Drosophila, for which all the current examples are, so it would look a little strange, I think.

**Comment by Phlya** [comment]
image
Here is a simple example with bigwigs (loss of K27me3 across HoxC in ES cells in 2i culture).

**Comment by Phlya** [comment]
There is a problem with `type = line` though, zero crossing are not shown and this makes the plot look weird - and fixing this is not trivial, would require interpolation to find positions of zero crossings and then extending the lines to there.
image
I tried doing this using fill_between with transparent facecolor, but then it show the line at zero with the same color, which is a little weird (just a small test example without pyGenomeTracks to show the problem). 
image
An option is to then add a line to show the zero level, which might be desirable anyway:
image
For now I added a warning that line plots with a different negative colour might produce ugly plots, but let me know if you would prefer a different solution.

**Comment by fidelram** [comment]
Thanks for the images. For the `type=line` I assume that when no negative color is given the result is as previous right? I am asking because in the code, when no negative color is given, then the same positive color is asigned. In the case of type=line, this could  cause the line to break as in the in the example that you sent. 

can you check this?

**Comment by Phlya** [comment]
See the commit above.

**Pull request merged**
