### PR TITLE
Narrow peak

### PR DESCRIPTION
**Pull request by lldelisle**
Solved the bug when there was no item in the region to plot. See #120

### CODE REVIEW

**Comment by LeilyR** [comment]
is this addressing `TypeError: cannot unpack non-iterable float object`. I make another branch please fetch current dev and add your changes and send your PR to the branch I will call it `narrowPeaks_debug`. I will later on merge it to develop. Thanks a lot!

**Comment by LeilyR** [comment]
Could please tell me which of the issue in #120 have been addressed in your PR, is it about the data type issue?

**Comment by lldelisle** [comment]
Sorry yes, it is only for the `TypeError: cannot unpack non-iterable float object`.
You want me to solve the log issue?

**Comment by LeilyR** [comment]
Ok thanks.
 As you wish, if you did it just send it as a PR to the same branch , otherwise i do that.

**Comment by LeilyR** [comment]
I have checked your code, unfortunately your proposal solution is not solving the issue the data type, in fact you even asked for the type change after where it complains . I will work on it myself , also fell free to have a second look and send a new PR only to this branch if you have anything else to add

**Comment by LeilyR** [comment]
fixed!

**Pull request merged**
