### PR TITLE
Hic matrix square

### PR DESCRIPTION
**Pull request by lldelisle**
I implemented a new track type which is like hicPlotMatrix.
I called it HiCMatrixSquareTrack. In ini file you need to put `file_type = hic_matrix_square`.
I am very bad at naming so if you want to change I have no objection.
I decided to create an abstract class HiCMatrixLikeTrack with 2 children: HiCMatrixTrack and HiCMatrixSquareTrack to avoid code duplications.
I think it would be good to implement loop_square and TAD_square to be able to overlap annotations on this.
I would have liked to be able to put a y axis in addition to the colorbar but this seems not easy before we implement real margin on the left.

### CODE REVIEW

**Review by joachimwolff — COMMENTED** [review]
Why is the last matrix in the test data having curves?

**Comment by lldelisle** [comment]
You mean that:
image

**Comment by lldelisle** [comment]
I guess it is because too long pairs have been filtered out before making the cool file...

**Review by joachimwolff — APPROVED** [review]

**Comment by lldelisle** [comment]
I don't understand why some linting are failing. In addition, they refer to a line which does not exists. @joachimwolff can you relaunch the CI?

**Pull request merged**
