### PR TITLE
Release 3.8

### PR DESCRIPTION
**Pull request by lldelisle**
Potential release text:

# 3.8

## Enhancement:

- A new ``type`` was introduced in 3.7 (announcement has been forgotten): a ``vhighlight`` to be able to hightlight a whole region across all tracks.
- Much more parameters for vhighlight and vlines
    - 'zorder' to set it on top or behind.
    - 'line_width', 'color', 'alpha', 'border_color' for vhighlight and 'line_style' for vlines
- You can now set multiple vlines
- For gtf, the output of ``make_tracks_file`` set ``prefered_name`` to ``gene_name`` instead of ``transcript_name``.

## Bugfix:

- Support mcool files for hic_matrix_square. This solves #404 
- Works with gffutils version 0.11.0 where ValueError became gffutils.exceptions.EmptyInputError for empty gtf.
- The installation instructions have been updated
- Fixed a small bug in links track with "use_middle" enabled, where midpoints could have different ordering than start points (Thanks to @Jeff1995 ).
- Fix a bug when plotting gtf in the middle of a large intron.
- Fix plot genes with ``orientation = inverted``
- Support Numpy 1.24, drop support below 1.20

## Relax version control on matplotlib:

- Any version of matplotlib from 3.1.1 to 3.6.2 is now accepted.

### CODE REVIEW

**Review by LeilyR — APPROVED** [review]
@lldelisle thanks!

**Comment by lldelisle** [comment]
There is a new build for cooler but the CI does not use it... I will wait for Monday.

**Comment by lldelisle** [comment]
It seems that mamba does not want to use the last build except if we specify `numpy >=1.16, <1.24`... Do you think we should write it into the dependencies?

**Comment by lldelisle** [comment]
I need to update HiCMatrix before we merge it.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
