### PR TITLE
fix cases when whole coding region is in a single intron

### PR DESCRIPTION
**Pull request by lldelisle**
This is a bug fix (that's why I PR to master).
When an exon had both UTR start and UTR end within it, only the UTR start was considered:
master_bed_arrow_zoom_before
I fixed it in both UCSC and flybase style (have a look to ng1 to ng4):
master_bed_arrow_zoom

### CODE REVIEW

**Comment by LeilyR** [comment]
what was the base of your branch? master or dev?

**Comment by lldelisle** [comment]
master

**Comment by LeilyR** [comment]
but you also changed the test files, right? this is not going to be so good since develop would still have the old test files. Do you mind if we still merge it into dev? Is it really necessary to have it out now? I suppose we are gonna tag a release in a month or 2. Is it possible for your users to use develop for the time being?

**Comment by lldelisle** [comment]
No problem to merge it into develop.

**Pull request merged**
