### PR TITLE
Replacing dependency to HiCExplorer by HiCMatrix

### PR DESCRIPTION
**Pull request by joachimwolff**
- Replace dependency of HiCExplorer by HiCMatrix.
- Fixing cooler read support, see #31

### CODE REVIEW

**Comment by fidelram** [comment]
I would like to prepare a new release. Do you think we should include these changes?

**Comment by joachimwolff** [comment]
It would be great if we could include them. It makes it possible to replace the content of hicPlotTADs with a call to pyGenomeTracks and therefore brings all new features and bugfixes to HiCExplorer.  With the current version we would have a mutual dependency of pyGenomeTracks and HiCExplorer.

**Comment by fidelram** [comment]
Thanks!

**Comment by joachimwolff** [comment]
@dpryan79 Do you have any idea why the bigwig test case with macOS is failing?

**Comment by dpryan79** [comment]
For some reason installing `configparser` results in numpy getting downgraded to an incompatible version for some bioconda packages. You can see that here: https://travis-ci.org/deeptools/pyGenomeTracks/jobs/426412361#L525-L542

Now you're probably asking why installing configparser would affect numpy/scipy/etc. I have no clue about that, it makes no sense. The fix would then be to install conigparser first and then the rest of the packages.

BTW, you could also stop testing python 2.7, it's going to die soon and numpy et al. are dropping support in a few months.

**Comment by fidelram** [comment]
When I have run into compatibility issues like this one, the way to go is to put all required modules in one file and conda takes care to install the common requirements. So, we can have a file called requirements2.7.txt that includes configparser and see if this solves the problem.

python 2.7 will be retired in 2020. I suggest we at least make this release compatible with python 2.7.

**Comment by joachimwolff** [comment]
My own, probably not reproducible, tests:
- Creating a new environment with python 2.7.15 and configparser --> No dependency to numpy
- Installing in an environment with already installed numpy --> Downgrade to numpy 1.13, sometimes 1.11
- Installing configparser in an environment without already installed numpy but installing numpy at the same time with newest version --> Dependency but it's ok install the newest version.

I do not understand this dependency cycle. Anyone? 
However, the last test case passes now by enforcing the newest numpy version in the requirements.txt file.

**Comment by dpryan79** [comment]
Conda's dependency resolution is truly a mystery.

**Pull request merged**
