### PR TITLE
added citation

### PR DESCRIPTION
**Pull request by vivekbhr**
just adding citation for now, but I would keep the branch for possible RTD integration.

### CODE REVIEW

**Comment by fidelram** [comment]
Vivek, can you add the citation text to the help message of the command line tools as well?

**Comment by vivekbhr** [comment]
@fidelram done.

**Comment by vivekbhr** [comment]
@fidelram python 2.7 error, shall I add # coding=utf-8 on top?

**Comment by fidelram** [comment]
I really don't know how to solve it. Try to add the encoding in the first line. If it does not work, simply remove the tilde from my last name.

**Pull request merged**
