### PR TITLE
Unify dependencies

### PR DESCRIPTION
**Pull request by lldelisle**
Hi,
I modified the files to be consistent between the versions and the dependencies between setup.py, requirements.txt and environment.yml.

### CODE REVIEW

**Comment by lldelisle** [comment]
- The only PR still open is the one with the x axis. I made a [PR](https://github.com/djakubosky/pyGenomeTracks/pull/1) to the author but he did not reply... Should I open a new PR to develop or should we wait?

- For the develop branch I suggest to regenerate all pictures (test and examples) with the develop version so people know what they can expect to have with the current version. But for this we should wait the last minute...

**Comment by bgruening** [comment]
> The only PR still open is the one with the x axis. I made a PR to the author but he did not reply... Should I open a new PR to develop or should we wait?

New PR seems fine to me. The commits should stay so everyone is acknowledged and in theory, the PR should also close themselves if all commits are merged. Let's try it.

> For the develop branch I suggest to regenerate all pictures (test and examples) with the develop version so people know what they can expect to have with the current version. But for this we should wait the last minute...

I need to check how much work that is. Thanks for the suggestion!

**Comment by lldelisle** [comment]
> > For the develop branch I suggest to regenerate all pictures (test and examples) with the develop version so people know what they can expect to have with the current version. But for this we should wait the last minute...
> 
> I need to check how much work that is. Thanks for the suggestion!
I think this should not be so hard if we decide to keep the ini files and generate a table with ini path, arguments and output... I can generate such a table and I have already the develop version installed locally.

**Comment by bgruening** [comment]
> I think this should not be so hard if we decide to keep the ini files and generate a table with ini path, arguments and output... I can generate such a table and I have already the develop version installed locally.

Awesome, thanks a lot. I will try to set up the auto-deploy. So we need to just tag a release going forwards and everything else happens automatically.

**Pull request merged**
