### PR TITLE
Readthedoc

### PR DESCRIPTION
**Pull request by lldelisle**
Hi,
I put all the README in rst files to be able to put them in readthedocs.
I added more examples.
For the authors, I put them in the order of the email but this is super open, I can put the one from setup.py.
Here is a preview:
[html_previous.tar.gz](https://github.com/deeptools/pyGenomeTracks/files/4105886/html_previous.tar.gz)

### CODE REVIEW

**Comment by lldelisle** [comment]
Oups problem with the table, I tell you when it is fixed.

**Comment by lldelisle** [comment]
Solved.
The installation page is mainly a copy paste from deeptools, I hope this is not an issue.
[html_preview.tar.gz](https://github.com/deeptools/pyGenomeTracks/files/4107816/html_preview.tar.gz)

**Comment by joachimwolff** [comment]
On which branch is this based on? I would like to merge it to a branch of develop to test if it is building with readthedocs.

**Comment by lldelisle** [comment]
May be you can create a branch dev_readthedoc and I will change the target.

**Pull request merged**
