### PR TITLE
Add ability to modulate alpha for track transparency

### PR DESCRIPTION
**Pull request by mikewolfe**
Allows user to change the alpha value and control transparency for all fill_between plots involving either bigwig or bedgraph files.

Particularly useful for overlaying multiple tracks on the same axis.

### CODE REVIEW

**Comment by joachimwolff** [comment]
Hi,

Thanks for your contribution.

To merge this PR, please rebase against the current development branch, change the 'merge into' to develop, add test cases for your changes and make sure you following out linting rules (flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E712).

Best,

Joachim

**Comment by mikewolfe** [comment]
With the changes from @lldelisle (thank you!) and the rebase against develop, I think this is ready to go.

**Comment by bgruening** [comment]
@mikewolfe I needed to rebase this against develop. Can you please ceck?

**Comment by bgruening** [comment]
Ok, we have a lot of changes in develop. Any help to test it is very very welcome!

**Comment by bgruening** [comment]
Thanks @mikewolfe!

**Pull request merged**
