### PR TITLE
add message if bedtools is not installed.

### PR DESCRIPTION
**Pull request by lldelisle**
Following #273 
I don't really like the print but I did not find another way.

### CODE REVIEW

**Comment by lldelisle** [comment]
Should I change print to:
```
sys.__stderr__.write("It seems that BEDTools is not installed. Cannot subset the file.")
```
The other option is to put log as parameter of `file_to_intervaltree` and `temp_file_from_intersect` and then use `log.warn`.
What do you think?

**Comment by joachimwolff** [comment]
How about this approach: 

- if all dependencies are present should be checked at installation time. I wonder a bit why it is not covered from our setup.py. There is already a part: https://github.com/deeptools/pyGenomeTracks/blob/master/setup.py#L93
- as additional checks: why don't we check it at every run of pgt at the start of the main function? And even more important, simply check if all dependencies are present, if not, throw an error and exit.

- I prefere to use `log` everywhere, similar to how it is used in HiCExplorer. I would do: 

```
log.error('dependency is missing')
exit(1)
```

**Comment by lldelisle** [comment]
So, you would not allow it to work when BEDTools is not present?
My idea was just to warn the user that it will be longer but you are probably right.

**Comment by lldelisle** [comment]
Hi,
I think the problem is that it is not a python dependency (pybedtools is the python dependency) but I don't know how to write an external dependency in the setup.py.
I don't like `exit(1)` because it is impossible to catch when you want to use it within python. I propose a more stringent version here: #284

**Comment by joachimwolff** [comment]
Conda has bedtools as a dependency of pybedtools.

- How is it with pip? 

The setup is just a python script, we could simply call pybedtools like you do in the source code. If it is successful we can continue with the installation, if not, we interrupt it.

**Comment by lldelisle** [comment]
pip also requires pybedtools, the problem is that pybedtools is working without bedtools, except if you call a bedtools command...
I know this is strange... You can create `pybedtools.BedTool` objects without bedtools but then when you do `object1.intersect(object2)` it fails... So to test it it is not just a import.

**Comment by joachimwolff** [comment]
We can test if the binary exists, similar to this solution:
https://stackoverflow.com/questions/377017/test-if-executable-exists-in-python

**Comment by lldelisle** [comment]
I prefer the #284 option just raise an error when you get a `notImplementedError` with a meaningful message.

**Comment by lldelisle** [comment]
#284 would give as output (only when bedtools is required):
```
$ bin/pgt --tracks ./pygenometracks/tests/test_data/bedgraph_useMid.ini --BED ./pygenometracks/tests/test_data/regions_imbricated_chr2.bed --trackLabelFraction 0.2 --width 38 --dpi 130  -o ./pygenometracks/tests/test_data/master_bedgraph_useMid.png
INFO:pygenometracks.tracksClass:initialize 1. [x-axis]
INFO:pygenometracks.tracksClass:initialize 2. [spacer]
INFO:pygenometracks.tracksClass:initialize 3. [test bedgraph]
ERROR:pygenometracks.utilities:BEDTools is not installed but required.
$
```

**Comment by joachimwolff** [comment]
We should give the users at least at the installation time a warning that not all dependencies are present. Maybe with the hint to use conda to avoid such trouble.

**Comment by lldelisle** [comment]
Hi,
Back on this question. I did not managed to make a test to be sure bedtools is installed at the time of installation before pybedtools is installed...
If someone wants to do it, no problem but for me, raising an error when you need it is sufficient.
If you want to mention conda I can add a message in the error like:
```
ERROR:pygenometracks.utilities:BEDTools is not installed but required, installation with conda would avoid this type of error.
```

**Review by joachimwolff — APPROVED** [review]

**Pull request merged**
