### PR TITLE
[WIP] release 3.3

### PR DESCRIPTION
**Pull request by lldelisle**
Of course **readthedocs** 
But also:
new features:
- progress bar for bed, gtf, bedgraph, narrowPeak, epilogos
- all colors can be set as `(r, g, b)` with r, g, b values between 0 and 1.
- all colormap can be set as an array of colors, for example  `[red, white, (0, 0, 0.5)]`
- the titles on the right can be align left, right or center with the argument `--trackLabelHAlign`
- for the links track, 
  - `compact_arcs_level` to be able to see both very long arcs and very small arcs.
  - `ylim` to be able to zoom and see small arcs.
- a new track type: `file_type = scalebar` which by default is close to the UCSC scale bar.
- for the bed tracks:
  - a new gene type: `tssarrow`
  - `border_color` and `color_utr` can be set to `bed_rgb`.
  - `all_labels_inside` allow to put the name of the region on the left if it ends after the plotted region.
  - `labels_in_margin` allow to put the name of the region in the margin if it ends after the plotted region.
- `line_width` can now be set in the narrowPeak tracks.
- `colormap` can now be set in bedgraphMatrix tracks.
bug fixes:
- if a bed with no interval is provided, pgt no longer exit.
- When an exon had both UTR start and UTR end within it, only the UTR start was considered.
- alpha in links tracks was not used
- qcat files with missing values are now working.

TODO/ToThink before merging:
- For the moment if the matrix is empty it stills stop.
If you ask for log/log1p and you have negative values with no NA it also stops.
Should we change it?

- Rerun the `pygenometracks/updateREADME.sh` to have the docs updated.

- Add more examples in readsthedocs?

### CODE REVIEW

**Comment by joachimwolff** [comment]
Looks good to me.

> For the moment if the matrix is empty it stills stop.
> If you ask for log/log1p and you have negative values with no NA it also stops.
> Should we change it?

Let's work on this for the next release.

> Rerun the pygenometracks/updateREADME.sh to have the docs updated.

I have done it, but no file was changed. Is this to be expected?

> Add more examples in readsthedocs?

We should extend readthedocs continuously. However, I think this is a silent update process and we don't need it for this release.

**Comment by lldelisle** [comment]
For the `hicmatrix >=12` you only want it in travis? I think it should be also in environment.yml and setup.py, no?

**Comment by lldelisle** [comment]
> I have done it, but no file was changed. Is this to be expected?

Yes if it was already updated, we do not expect any change.

**Comment by lldelisle** [comment]
For me it is good. Should we wait for more approvements?

**Comment by joachimwolff** [comment]
@lldelisle Thanks a lot for your hard work on this project! :tada:

**Comment by lldelisle** [comment]
How do we update bioconda? Is there a bot checking for updates or do we need to do something?

**Comment by joachimwolff** [comment]
I checked bioconda: The last times a bot recognized a new release and created a PR. Let's wait a bit if it works this time too.

**Comment by joachimwolff** [comment]
It is merged. Version 3.3. should be available soon in bioconda.

**Comment by lldelisle** [comment]
The dependencies of the recipe has not been updated...
tqdm is missing. I think we should do a manual PR.
Should I put hicmatrix >=12?

**Comment by joachimwolff** [comment]
We still have >=11 there? I think we can leave it as it is and enforce it with the next update.

**Comment by lldelisle** [comment]
We have >=9...
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pygenometracks/meta.yaml

**Comment by lldelisle** [comment]
```
    - python >=3.6
    - numpy >=1.16
    - matplotlib >=3.0
    - intervaltree >=2.1.0
    - pybigwig >=0.3.4
    - future >=0.17.0
    - hicmatrix >=9
    - pysam >=0.14
    - gffutils >=0.9
```
For me the main issue is tqdm...

**Pull request merged**
